import Phaser from 'phaser';
import { COLORS, DEPTHS, FONT_FAMILY, MENU_LAYOUT, TEXT_STYLES, BattleNodeData } from '../constants';
import { TimelineManager } from '../ui/timeline_manager';
import { BattleModal } from '../ui/battle_modal';
import { PolishEagle } from '../sprites/polish_eagle';
import { generateHussarTextures } from '../sprites/hussar_sprite';

export class MenuScene extends Phaser.Scene {
  private bgGraphics!: Phaser.GameObjects.Graphics;
  private decorGraphics!: Phaser.GameObjects.Graphics;
  private titleGraphics!: Phaser.GameObjects.Graphics;
  private timeline?: TimelineManager;
  private eagle?: PolishEagle;
  private hussar?: Phaser.GameObjects.Sprite;
  private hussarBaseY: number = 0;
  private selectedBattleText?: Phaser.GameObjects.Text;
  private particles?: Phaser.GameObjects.Particles.ParticleEmitter;
  private activeModal?: BattleModal;

  constructor() {
    super({ key: 'MenuScene' });
  }

  create(): void {
    const { width, height } = this.scale;

    this.cameras.main.fadeIn(800);

    this.createBackground(width, height);
    this.createDecorativeStripes(width, height);
    this.createTitle(width);
    this.createSelectedBattleText(width);
    this.createTimeline(width);
    this.createSprites();
    this.createParticles(width, height);

    this.events.once(Phaser.Scenes.Events.SHUTDOWN, this.onShutdown, this);
  }

  private createBackground(width: number, height: number): void {
    this.add
      .rectangle(width / 2, height / 2, width, height, COLORS.BG_BASE)
      .setDepth(DEPTHS.BG);

    this.add
      .rectangle(
        width / 2,
        height / 2,
        width - MENU_LAYOUT.PANEL_MARGIN * 2,
        height - MENU_LAYOUT.PANEL_MARGIN * 2,
        COLORS.BG_PANEL,
      )
      .setDepth(DEPTHS.PANEL);

    this.bgGraphics = this.add.graphics().setDepth(DEPTHS.PANEL);
    this.bgGraphics.lineStyle(2, COLORS.WHITE, 0.3);
    this.bgGraphics.strokeRect(
      MENU_LAYOUT.SEPARATOR_INSET,
      MENU_LAYOUT.SEPARATOR_INSET,
      width - MENU_LAYOUT.SEPARATOR_INSET * 2,
      height - MENU_LAYOUT.SEPARATOR_INSET * 2,
    );
  }

  private createDecorativeStripes(width: number, height: number): void {
    this.decorGraphics = this.add.graphics().setDepth(DEPTHS.DECORATIONS);

    this.decorGraphics.fillStyle(COLORS.RED, 0.7);
    this.decorGraphics.fillRect(0, 0, width, MENU_LAYOUT.STRIPE_HEIGHT);
    this.decorGraphics.fillRect(0, height - MENU_LAYOUT.STRIPE_HEIGHT, width, MENU_LAYOUT.STRIPE_HEIGHT);

    this.decorGraphics.fillStyle(COLORS.WHITE, 0.15);
    this.decorGraphics.fillRect(0, MENU_LAYOUT.STRIPE_HEIGHT, width, MENU_LAYOUT.WHITE_STRIPE_HEIGHT);
    this.decorGraphics.fillRect(
      0,
      height - MENU_LAYOUT.STRIPE_HEIGHT - MENU_LAYOUT.WHITE_STRIPE_HEIGHT,
      width,
      MENU_LAYOUT.WHITE_STRIPE_HEIGHT,
    );
  }

  private createTitle(width: number): void {
    this.add
      .text(width / 2, MENU_LAYOUT.TITLE_Y, 'HISTORY OF POLAND', TEXT_STYLES.TITLE)
      .setOrigin(0.5)
      .setDepth(DEPTHS.UI);

    this.add
      .text(width / 2, MENU_LAYOUT.SUBTITLE_Y, '— TOWER DEFENSE —', TEXT_STYLES.SUBTITLE)
      .setOrigin(0.5)
      .setDepth(DEPTHS.UI);

    this.titleGraphics = this.add.graphics().setDepth(DEPTHS.UI);
    this.titleGraphics.lineStyle(2, COLORS.GOLD, 0.8);
    this.titleGraphics.lineBetween(
      width / 2 - MENU_LAYOUT.DECO_LINE_HALF_WIDTH,
      MENU_LAYOUT.DECO_LINE_Y,
      width / 2 + MENU_LAYOUT.DECO_LINE_HALF_WIDTH,
      MENU_LAYOUT.DECO_LINE_Y,
    );
    this.titleGraphics.lineStyle(1, COLORS.GOLD, 0.4);
    this.titleGraphics.lineBetween(
      width / 2 - MENU_LAYOUT.DECO_LINE_OUTER_HALF_WIDTH,
      MENU_LAYOUT.DECO_LINE_Y + 4,
      width / 2 + MENU_LAYOUT.DECO_LINE_OUTER_HALF_WIDTH,
      MENU_LAYOUT.DECO_LINE_Y + 4,
    );
  }

  update(time: number, _delta: number): void {
    const pointer = this.input.activePointer;
    if (this.timeline && pointer) {
      this.timeline.update(pointer);
    }

    // Hussar idle bob animation
    if (this.hussar) {
      this.hussar.y = this.hussarBaseY + Math.sin(time * 0.002) * 4;
    }
  }

  private createSelectedBattleText(width: number): void {
    this.selectedBattleText = this.add
      .text(width / 2, MENU_LAYOUT.SELECTED_BATTLE_Y, 'Wybierz bitwę na osi czasu', {
        fontFamily: FONT_FAMILY,
        fontSize: '20px',
        color: '#ffd700',
      })
      .setOrigin(0.5)
      .setDepth(DEPTHS.UI);
  }

  private createTimeline(width: number): void {
    this.timeline = new TimelineManager(
      this,
      (data: BattleNodeData) => {
        this.selectedBattleText!.setText(`Wybrana bitwa: ${data.name} (${data.year})`);
        this.activeModal?.destroy();
        this.activeModal = new BattleModal(this, data);
      },
    );
  }

  private createSprites(): void {
    // Polish Eagle (right side)
    this.eagle = new PolishEagle(this, MENU_LAYOUT.EAGLE_X, MENU_LAYOUT.SPRITES_Y, 1.4);

    // Hussar sprite (left side) - textures pre-generated by BootScene
    if (!this.textures.exists('hussar-frame-0')) {
      console.warn('[MenuScene] Hussar textures missing - regenerating (BootScene may have been skipped)');
      generateHussarTextures(this);
    }
    this.hussarBaseY = MENU_LAYOUT.SPRITES_Y;
    this.hussar = this.add.sprite(MENU_LAYOUT.HUSSAR_X, this.hussarBaseY, 'hussar-frame-0');
    this.hussar.setDepth(DEPTHS.SPRITES);
    this.hussar.setScale(1.2);
    this.hussar.play('hussar-gallop');
  }

  private createParticles(width: number, height: number): void {
    // Texture pre-generated by BootScene; regenerate as fallback if scene was entered directly
    if (!this.textures.exists('white-particle')) {
      const particleGfx = this.add.graphics();
      particleGfx.fillStyle(0xffffff, 1);
      particleGfx.fillRect(0, 0, 4, 4);
      particleGfx.generateTexture('white-particle', 4, 4);
      particleGfx.destroy();
    }

    // White dust particles drifting upward
    this.particles = this.add.particles(width / 2, height, 'white-particle', {
      x: { min: -width / 2, max: width / 2 },
      y: 0,
      speedY: { min: -60, max: -20 },
      alpha: { start: 0.3, end: 0 },
      lifespan: { min: 4000, max: 8000 },
      frequency: 100,
      quantity: 2,
    });
    this.particles.setDepth(DEPTHS.DECORATIONS);
  }

  private onShutdown(): void {
    this.activeModal?.destroy();
    this.bgGraphics?.destroy();
    this.decorGraphics?.destroy();
    this.titleGraphics?.destroy();
    this.timeline?.destroy();
    this.eagle?.destroy();
    this.hussar?.destroy();
    this.selectedBattleText?.destroy();
    this.particles?.stop();
    this.particles?.destroy();
  }
}
